server:
  port: 8083

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:8084
#  profiles:
#    active: dev
  cloud:
    gateway:
      route:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
            -
        - id: ATTENDANCE-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/attendance/**


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
